#!/bin/sh
# if command -v sxhkd &> /dev/null; then
  # sxhkd
# fi &
# \xset r rate 300 50 &
# \setxkbmap -option grp:alt_shift_toggle -option ctrl:nocaps -layout us,ru
USERXSESSION="$XDG_CACHE_HOME/x11/xsession"
USERXSESSIONRC="$XDG_CACHE_HOME/x11/xsessionrc"
ALTUSERXSESSION="$XDG_CACHE_HOME/x11/Xsession"
ERRFILE="$XDG_CACHE_HOME/x11/xsession-errors"
